spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bbdd_pedidos?serverTimezone=UTC
    username: root
    password: M1l.n0y.p3.R00t
  jpa:
    hibernate:
      naming:
        implicitStrategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physicalStrategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
eureka:
  client:
  serviceUrl:
    defaultZone: http://localhost:8761/eureka
  instance:
    hostName: 192.168.1.55 #Se hace para que el microservicio se registre en eureka con la dirección ip de la máquina  ya que el nombre que utiliza puede que el gateway no lo pueda resolver
server:
  port: 8000
  servlet:
    contextPath: /productos
